name: Docker Release (GHCR)

on:
  # Bouton "Run workflow" dans l’onglet Actions
  workflow_dispatch:

  # Déclenche aussi sur push (pratique pour tester)
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-release.yml'

  # Déclenche lors d'une release publiée par semantic-release
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare vars
        id: prep
        shell: bash
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER}"
          IMAGE="smartpitch-backend"
          echo "owner_lc=${OWNER,,}" >> $GITHUB_OUTPUT
          echo "image=${IMAGE,,}" >> $GITHUB_OUTPUT

          # Tag "joli" si release, sinon "latest"
          TAG="${GITHUB_REF_NAME:-${GITHUB_EVENT_RELEASE_TAG_NAME:-latest}}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "tag_clean=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.prep.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.prep.outputs.owner_lc }}/${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag_clean }}
            ghcr.io/${{ steps.prep.outputs.owner_lc }}/${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
